'use strict';

// ============================================================================
// DATA EXTRACTION HELPERS
// ============================================================================

/**
 * Extract simplified brand data
 */
function extractSimplifiedBrand(brand) {
  return {
    name: brand.name,
    priorityOver: brand.priorityOver || [],
    regexpBin: brand.regexpBin,
    regexpFull: brand.regexpFull,
    regexpCvv: brand.regexpCvv,
  };
}

/**
 * Extract detailed brand data
 */
function extractDetailedBrand(brand) {
  return {
    scheme: brand.scheme,
    brand: brand.brand,
    type: brand.type,
    number: brand.number,
    cvv: brand.cvv,
    patterns: brand.patterns,
    countries: brand.countries,
    metadata: brand.metadata || {},
    priorityOver: brand.priorityOver || [],
    bins: brand.bins || [],
  };
}

/**
 * Generate file header comment
 */
function fileHeader(commentPrefix = '//') {
  return [
    `${commentPrefix} Auto-generated by bin-cc build - DO NOT EDIT`,
    `${commentPrefix} Generated: ${new Date().toISOString()}`,
  ];
}

module.exports = {
  extractSimplifiedBrand,
  extractDetailedBrand,
  fileHeader,
};
